spring:
  datasource:
    url: jdbc:mysql://localhost:3306/padeldb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Madrid
    username: root
    #password: mysecretpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #defer-datasource-initialization: always
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate.format_sql: true
        hibernate.jdbc.time_zone: Europe/Madrid
      dialect: org.hibernate.dialect.MySQL8Dialect
  #logging.level.org.springframework.jdbc.core.JdbcTemplate: DEBUG
  sql:
    init:
     # mode: always
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

telegram:
  bot:
    username: PadelMachBot
    token: 5582112657:AAEvou_LaQ-TpLYhynfG4aQOzfFl7Ct3qxc
springdoc:
  swagger-ui:
    url: /apiPadel.yaml

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.padelapp: DEBUG
  file: ./log/-de-registro.log

server:
  forward-headers-strategy: framework